"""empty message

Revision ID: 7825757bf5e9
Revises: 1d82e1f95f3e
Create Date: 2021-04-14 02:05:29.260669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7825757bf5e9'
down_revision = '1d82e1f95f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cars', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    # ### end Alembic commands ###
